# Generated by Django 2.2.6 on 2019-11-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='detail',
            field=models.TextField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
