# Generated by Django 2.2.6 on 2019-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191119_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='detail',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
