# Generated by Django 2.2.6 on 2019-11-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191119_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.FileField(null=True, upload_to='upload'),
        ),
    ]
