# Generated by Django 2.2.6 on 2019-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191119_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='img',
            field=models.FileField(null=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.FileField(null=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='img',
            field=models.FileField(null=True, upload_to='static/image/'),
        ),
    ]
