# Generated by Django 2.2.6 on 2019-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20191119_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
    ]
