# Generated by Django 2.2.6 on 2019-11-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_choice_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='quiz',
        ),
    ]
