# Generated by Django 2.2.6 on 2019-11-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_choice_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(max_length=1000),
        ),
    ]
